extends Node

signal country_purchased(country: Dictionary)

var owned: Array = []

const COUNTRIES := [
	{"id":"fji","name":"Fiji","lon":178.0,"lat":-17.8,"gdp":5.5,"pop":0.9,"price":5,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "fji_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"tza","name":"United Republic of Tanzania","lon":35.0,"lat":-6.1,"gdp":63.2,"pop":58.0,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "tza_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"sah","name":"Western Sahara","lon":-12.6,"lat":24.0,"gdp":0.9,"pop":0.6,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "sah_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"can","name":"Canada","lon":-101.9,"lat":60.3,"gdp":2.1,"pop":38,"price":55,"region":"N America","color":"#E24B4A","amb_actions":[{"id": "ca_oil", "label": "Alberta oil sands expansion", "cost": 300000, "effect": "ticker", "ticker": "WTI", "mag": 0.03, "cd": 21}]},
	{"id":"usa","name":"United States of America","lon":-97.5,"lat":39.5,"gdp":25.0,"pop":335,"price":500,"region":"N America","color":"#378ADD","amb_actions":[{"id": "usa_rates", "label": "Pressure Fed toward rate cut", "cost": 2000000, "effect": "global", "mag": 0.03, "cd": 30}, {"id": "usa_tech", "label": "Ease tech antitrust enforcement", "cost": 1500000, "effect": "sector", "sector": "Tech", "mag": 0.04, "cd": 21}, {"id": "usa_sanction", "label": "Impose export sanctions", "cost": 3000000, "effect": "sector", "sector": "Tech", "mag": -0.06, "cd": 45}]},
	{"id":"kaz","name":"Kazakhstan","lon":68.7,"lat":49.1,"gdp":181.7,"pop":18.5,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "kaz_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"uzb","name":"Uzbekistan","lon":64.0,"lat":41.7,"gdp":57.9,"pop":33.6,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "uzb_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"png","name":"Papua New Guinea","lon":143.9,"lat":-5.7,"gdp":24.8,"pop":8.8,"price":5,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "png_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"idn","name":"Indonesia","lon":101.9,"lat":-1.0,"gdp":1.4,"pop":275,"price":36,"region":"Asia","color":"#E24B4A","amb_actions":[{"id": "id_nickel", "label": "Nickel export ban (EV impact)", "cost": 200000, "effect": "ticker", "ticker": "ELVT", "mag": -0.04, "cd": 21}]},
	{"id":"arg","name":"Argentina","lon":-64.2,"lat":-33.5,"gdp":0.6,"pop":46,"price":18,"region":"S America","color":"#534AB7","amb_actions":[{"id": "ar_lithium", "label": "Lithium cartel formation", "cost": 100000, "effect": "ticker", "ticker": "ELVT", "mag": -0.03, "cd": 21}]},
	{"id":"chl","name":"Chile","lon":-72.3,"lat":-38.2,"gdp":282.3,"pop":19.0,"price":9,"region":"S America","color":"#639922","amb_actions":[{"id": "chl_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"cod","name":"Democratic Republic of the Congo","lon":23.5,"lat":-1.9,"gdp":50.4,"pop":86.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "cod_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"som","name":"Somalia","lon":45.2,"lat":3.6,"gdp":4.7,"pop":10.2,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "som_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"ken","name":"Kenya","lon":37.9,"lat":0.5,"gdp":95.5,"pop":52.6,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "ken_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"sdn","name":"Sudan","lon":29.3,"lat":16.3,"gdp":30.5,"pop":42.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "sdn_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"tcd","name":"Chad","lon":18.6,"lat":15.1,"gdp":11.3,"pop":15.9,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "tcd_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"hti","name":"Haiti","lon":-72.2,"lat":19.3,"gdp":14.3,"pop":11.3,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "hti_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"dom","name":"Dominican Republic","lon":-70.7,"lat":19.1,"gdp":88.9,"pop":10.7,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "dom_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"rus","name":"Russia","lon":44.7,"lat":58.2,"gdp":1.8,"pop":144,"price":36,"region":"Asia","color":"#888780","amb_actions":[{"id": "ru_gas", "label": "Cut natural gas supply to Europe", "cost": 600000, "effect": "ticker", "ticker": "NTG", "mag": 0.1, "cd": 30}, {"id": "ru_oil", "label": "Announce OPEC+ cut extension", "cost": 500000, "effect": "ticker", "ticker": "WTI", "mag": 0.06, "cd": 21}]},
	{"id":"bhs","name":"The Bahamas","lon":-77.1,"lat":26.4,"gdp":13.6,"pop":0.4,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "bhs_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"flk","name":"Falkland Islands","lon":-58.7,"lat":-51.6,"gdp":0.3,"pop":0.0,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "flk_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"nor","name":"Norway","lon":9.7,"lat":61.4,"gdp":0.6,"pop":5,"price":22,"region":"Europe","color":"#1D9E75","amb_actions":[{"id": "no_sovereign", "label": "Oil fund reallocation signal", "cost": 200000, "effect": "global", "mag": 0.025, "cd": 21}]},
	{"id":"grl","name":"Greenland","lon":-39.3,"lat":74.3,"gdp":3.1,"pop":0.1,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "grl_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"atf","name":"French Southern and Antarctic Lands","lon":69.1,"lat":-49.3,"gdp":0.0,"pop":0.0,"price":5,"region":"Other","color":"#666666","amb_actions":[{"id": "atf_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"tls","name":"East Timor","lon":125.9,"lat":-8.8,"gdp":2.0,"pop":1.3,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "tls_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"zaf","name":"South Africa","lon":23.7,"lat":-29.7,"gdp":0.4,"pop":60,"price":15,"region":"Africa","color":"#888780","amb_actions":[{"id": "za_gold", "label": "Gold miners strike threat", "cost": 80000, "effect": "ticker", "ticker": "XAU", "mag": 0.04, "cd": 14}]},
	{"id":"lso","name":"Lesotho","lon":28.2,"lat":-29.5,"gdp":2.4,"pop":2.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "lso_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"mex","name":"Mexico","lon":-102.3,"lat":23.9,"gdp":1.3,"pop":128,"price":34,"region":"N America","color":"#639922","amb_actions":[{"id": "mx_nearshore", "label": "Manufacturing nearshoring deal", "cost": 150000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 14}]},
	{"id":"ury","name":"Uruguay","lon":-56.0,"lat":-33.0,"gdp":56.0,"pop":3.5,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "ury_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"bra","name":"Brazil","lon":-49.6,"lat":-12.1,"gdp":2.1,"pop":215,"price":52,"region":"S America","color":"#639922","amb_actions":[{"id": "br_commodities", "label": "Amazon mining concession", "cost": 250000, "effect": "ticker", "ticker": "XAG", "mag": 0.04, "cd": 14}, {"id": "br_oil", "label": "Pre-salt oil field announcement", "cost": 300000, "effect": "ticker", "ticker": "WTI", "mag": 0.03, "cd": 21}]},
	{"id":"bol","name":"Bolivia","lon":-64.6,"lat":-16.7,"gdp":40.9,"pop":11.5,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "bol_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"per","name":"Peru","lon":-72.9,"lat":-13.0,"gdp":226.8,"pop":32.5,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "per_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"col","name":"Colombia","lon":-73.2,"lat":3.4,"gdp":323.6,"pop":50.3,"price":10,"region":"S America","color":"#639922","amb_actions":[{"id": "col_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"pan","name":"Panama","lon":-80.4,"lat":8.7,"gdp":66.8,"pop":4.2,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "pan_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"cri","name":"Costa Rica","lon":-84.1,"lat":10.1,"gdp":61.8,"pop":5.0,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "cri_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"nic","name":"Nicaragua","lon":-85.1,"lat":12.7,"gdp":12.5,"pop":6.5,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "nic_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"hnd","name":"Honduras","lon":-86.9,"lat":14.8,"gdp":25.1,"pop":9.7,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "hnd_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"slv","name":"El Salvador","lon":-88.9,"lat":13.7,"gdp":27.0,"pop":6.5,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "slv_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"gtm","name":"Guatemala","lon":-90.5,"lat":15.0,"gdp":76.7,"pop":16.6,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "gtm_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"blz","name":"Belize","lon":-88.7,"lat":17.2,"gdp":1.9,"pop":0.4,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "blz_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"ven","name":"Venezuela","lon":-64.6,"lat":7.2,"gdp":482.4,"pop":28.5,"price":6,"region":"S America","color":"#639922","amb_actions":[{"id": "ven_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"guy","name":"Guyana","lon":-58.9,"lat":5.1,"gdp":5.2,"pop":0.8,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "guy_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"sur","name":"Suriname","lon":-55.9,"lat":4.1,"gdp":3.7,"pop":0.6,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "sur_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"fra","name":"France","lon":2.6,"lat":46.7,"gdp":2.9,"pop":68,"price":72,"region":"Europe","color":"#534AB7","amb_actions":[{"id": "fr_luxury", "label": "Luxury export tariff removal", "cost": 350000, "effect": "sector", "sector": "Finance", "mag": 0.025, "cd": 14}, {"id": "fr_energy", "label": "Nuclear energy expansion", "cost": 500000, "effect": "sector", "sector": "Energy", "mag": -0.03, "cd": 21}]},
	{"id":"ecu","name":"Ecuador","lon":-78.2,"lat":-1.3,"gdp":107.4,"pop":17.4,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "ecu_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"pri","name":"Puerto Rico","lon":-66.5,"lat":18.2,"gdp":105.0,"pop":3.2,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "pri_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"jam","name":"Jamaica","lon":-77.3,"lat":18.1,"gdp":16.5,"pop":2.9,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "jam_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"cub","name":"Cuba","lon":-78.0,"lat":21.3,"gdp":100.0,"pop":11.3,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "cub_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"zwe","name":"Zimbabwe","lon":29.9,"lat":-18.9,"gdp":21.4,"pop":14.6,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "zwe_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"bwa","name":"Botswana","lon":24.2,"lat":-22.1,"gdp":18.3,"pop":2.3,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "bwa_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"nam","name":"Namibia","lon":17.1,"lat":-20.6,"gdp":12.4,"pop":2.5,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "nam_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"sen","name":"Senegal","lon":-14.8,"lat":15.1,"gdp":23.6,"pop":16.3,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "sen_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"mli","name":"Mali","lon":-2.0,"lat":18.7,"gdp":17.3,"pop":19.7,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "mli_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"mrt","name":"Mauritania","lon":-9.7,"lat":19.6,"gdp":7.6,"pop":4.5,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "mrt_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"ben","name":"Benin","lon":2.4,"lat":10.3,"gdp":14.4,"pop":11.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "ben_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"ner","name":"Niger","lon":9.5,"lat":17.4,"gdp":12.9,"pop":23.3,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "ner_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"nga","name":"Nigeria","lon":7.5,"lat":9.4,"gdp":0.5,"pop":220,"price":14,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "ng_oil", "label": "Niger Delta supply disruption", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.03, "cd": 14}]},
	{"id":"cmr","name":"Cameroon","lon":12.5,"lat":4.6,"gdp":39.0,"pop":25.9,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "cmr_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"tgo","name":"Togo","lon":1.1,"lat":8.8,"gdp":5.5,"pop":8.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "tgo_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"gha","name":"Ghana","lon":-1.0,"lat":7.7,"gdp":67.0,"pop":30.4,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "gha_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"civ","name":"Ivory Coast","lon":-5.6,"lat":7.5,"gdp":58.5,"pop":25.7,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "civ_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"gin","name":"Guinea","lon":-10.0,"lat":10.6,"gdp":12.3,"pop":12.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "gin_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"gnb","name":"Guinea-Bissau","lon":-14.5,"lat":12.2,"gdp":1.3,"pop":1.9,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "gnb_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"lbr","name":"Liberia","lon":-9.5,"lat":6.4,"gdp":3.1,"pop":4.9,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "lbr_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"sle","name":"Sierra Leone","lon":-11.8,"lat":8.6,"gdp":4.1,"pop":7.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "sle_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"bfa","name":"Burkina Faso","lon":-1.4,"lat":12.7,"gdp":16.0,"pop":20.3,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "bfa_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"caf","name":"Central African Republic","lon":20.9,"lat":7.0,"gdp":2.2,"pop":4.7,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "caf_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"cog","name":"Republic of the Congo","lon":15.9,"lat":0.1,"gdp":12.3,"pop":5.4,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "cog_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"gab","name":"Gabon","lon":11.8,"lat":-0.4,"gdp":16.9,"pop":2.2,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "gab_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"gnq","name":"Equatorial Guinea","lon":9.0,"lat":2.3,"gdp":11.0,"pop":1.4,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "gnq_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"zmb","name":"Zambia","lon":26.4,"lat":-14.7,"gdp":23.3,"pop":17.9,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "zmb_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"mwi","name":"Malawi","lon":33.6,"lat":-13.4,"gdp":7.7,"pop":18.6,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "mwi_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"moz","name":"Mozambique","lon":37.8,"lat":-13.9,"gdp":15.3,"pop":30.4,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "moz_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"swz","name":"eSwatini","lon":31.5,"lat":-26.5,"gdp":4.5,"pop":1.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "swz_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"ago","name":"Angola","lon":18.0,"lat":-12.2,"gdp":88.8,"pop":31.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "ago_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"bdi","name":"Burundi","lon":29.9,"lat":-3.3,"gdp":3.0,"pop":11.5,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "bdi_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"isr","name":"Israel","lon":34.8,"lat":30.9,"gdp":394.7,"pop":9.1,"price":13,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "isr_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"lbn","name":"Lebanon","lon":36.0,"lat":34.1,"gdp":52.0,"pop":6.9,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "lbn_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"mdg","name":"Madagascar","lon":46.7,"lat":-18.6,"gdp":14.1,"pop":27.0,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "mdg_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"psx","name":"Palestine","lon":35.3,"lat":32.0,"gdp":16.3,"pop":4.7,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "psx_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"gmb","name":"Gambia","lon":-15.0,"lat":13.6,"gdp":1.8,"pop":2.3,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "gmb_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"tun","name":"Tunisia","lon":9.0,"lat":33.7,"gdp":38.8,"pop":11.7,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "tun_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"dza","name":"Algeria","lon":2.8,"lat":27.4,"gdp":171.1,"pop":43.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "dza_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"jor","name":"Jordan","lon":36.4,"lat":30.8,"gdp":44.5,"pop":10.1,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "jor_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"are","name":"United Arab Emirates","lon":54.5,"lat":23.5,"gdp":0.5,"pop":10,"price":20,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "ae_sovereign", "label": "Sovereign wealth fund signal", "cost": 150000, "effect": "global", "mag": 0.02, "cd": 14}]},
	{"id":"qat","name":"Qatar","lon":51.1,"lat":25.2,"gdp":175.8,"pop":2.8,"price":12,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "qat_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"kwt","name":"Kuwait","lon":47.3,"lat":29.4,"gdp":134.6,"pop":4.2,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "kwt_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"irq","name":"Iraq","lon":43.3,"lat":33.1,"gdp":234.1,"pop":39.3,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "irq_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"omn","name":"Oman","lon":57.3,"lat":22.1,"gdp":76.3,"pop":5.0,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "omn_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"vut","name":"Vanuatu","lon":166.9,"lat":-15.4,"gdp":0.9,"pop":0.3,"price":5,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "vut_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"khm","name":"Cambodia","lon":104.5,"lat":12.6,"gdp":27.1,"pop":16.5,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "khm_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"tha","name":"Thailand","lon":101.1,"lat":15.5,"gdp":543.5,"pop":69.6,"price":16,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "tha_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"lao","name":"Laos","lon":102.5,"lat":19.4,"gdp":18.2,"pop":7.2,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "lao_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"mmr","name":"Myanmar","lon":95.8,"lat":21.6,"gdp":76.1,"pop":54.0,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "mmr_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"vnm","name":"Vietnam","lon":105.4,"lat":21.7,"gdp":261.9,"pop":96.5,"price":9,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "vnm_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"prk","name":"North Korea","lon":126.4,"lat":39.9,"gdp":40.0,"pop":25.7,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "prk_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"kor","name":"South Korea","lon":128.1,"lat":36.4,"gdp":1.7,"pop":52,"price":52,"region":"Asia","color":"#378ADD","amb_actions":[{"id": "kr_chips", "label": "Semiconductor export controls", "cost": 400000, "effect": "ticker", "ticker": "CHPX", "mag": -0.05, "cd": 21}]},
	{"id":"mng","name":"Mongolia","lon":104.2,"lat":46.0,"gdp":14.0,"pop":3.2,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "mng_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"ind","name":"India","lon":79.4,"lat":22.7,"gdp":3.5,"pop":1400,"price":95,"region":"Asia","color":"#EF9F27","amb_actions":[{"id": "in_it", "label": "Offshore IT contracts windfall", "cost": 300000, "effect": "sector", "sector": "Tech", "mag": 0.025, "cd": 14}, {"id": "in_oil", "label": "Major oil import announcement", "cost": 400000, "effect": "ticker", "ticker": "WTI", "mag": 0.03, "cd": 21}]},
	{"id":"bgd","name":"Bangladesh","lon":89.7,"lat":24.2,"gdp":302.6,"pop":163.0,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "bgd_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"btn","name":"Bhutan","lon":90.0,"lat":27.5,"gdp":2.5,"pop":0.8,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "btn_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"npl","name":"Nepal","lon":83.6,"lat":28.3,"gdp":30.6,"pop":28.6,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "npl_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"pak","name":"Pakistan","lon":68.5,"lat":29.3,"gdp":278.2,"pop":216.6,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "pak_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"afg","name":"Afghanistan","lon":66.5,"lat":34.2,"gdp":19.3,"pop":38.0,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "afg_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"tjk","name":"Tajikistan","lon":72.6,"lat":38.2,"gdp":8.1,"pop":9.3,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "tjk_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"kgz","name":"Kyrgyzstan","lon":74.5,"lat":41.7,"gdp":8.5,"pop":6.5,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "kgz_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"tkm","name":"Turkmenistan","lon":58.7,"lat":39.9,"gdp":40.8,"pop":5.9,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "tkm_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"irn","name":"Iran","lon":54.9,"lat":32.2,"gdp":454.0,"pop":82.9,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "irn_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"syr","name":"Syria","lon":38.3,"lat":35.0,"gdp":98.8,"pop":17.1,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "syr_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"arm","name":"Armenia","lon":44.8,"lat":40.5,"gdp":13.7,"pop":3.0,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "arm_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"swe","name":"Sweden","lon":19.0,"lat":65.9,"gdp":530.9,"pop":10.3,"price":15,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "swe_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"blr","name":"Belarus","lon":28.4,"lat":53.8,"gdp":63.1,"pop":9.5,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "blr_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"ukr","name":"Ukraine","lon":32.1,"lat":49.7,"gdp":153.8,"pop":44.4,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "ukr_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"pol","name":"Poland","lon":19.5,"lat":52.0,"gdp":595.9,"pop":38.0,"price":17,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "pol_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"aut","name":"Austria","lon":14.1,"lat":47.5,"gdp":445.1,"pop":8.9,"price":12,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "aut_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"hun","name":"Hungary","lon":19.4,"lat":47.1,"gdp":163.5,"pop":9.8,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "hun_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"mda","name":"Moldova","lon":28.5,"lat":47.4,"gdp":12.0,"pop":2.7,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "mda_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"rou","name":"Romania","lon":25.0,"lat":45.7,"gdp":250.1,"pop":19.4,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "rou_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"ltu","name":"Lithuania","lon":24.1,"lat":55.1,"gdp":54.6,"pop":2.8,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "ltu_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"lva","name":"Latvia","lon":25.5,"lat":57.1,"gdp":34.1,"pop":1.9,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "lva_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"est","name":"Estonia","lon":25.9,"lat":58.7,"gdp":31.5,"pop":1.3,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "est_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"deu","name":"Germany","lon":9.7,"lat":51.0,"gdp":4.0,"pop":84,"price":80,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "de_ecb", "label": "Push ECB toward rate cut", "cost": 500000, "effect": "sector", "sector": "Finance", "mag": 0.03, "cd": 21}, {"id": "de_industry", "label": "Industrial export deal", "cost": 300000, "effect": "sector", "sector": "Tech", "mag": 0.02, "cd": 14}]},
	{"id":"bgr","name":"Bulgaria","lon":25.2,"lat":42.5,"gdp":68.6,"pop":7.0,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "bgr_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"grc","name":"Greece","lon":21.7,"lat":39.5,"gdp":209.9,"pop":10.7,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "grc_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"tur","name":"Turkey","lon":34.5,"lat":39.3,"gdp":0.9,"pop":85,"price":26,"region":"Europe","color":"#E24B4A","amb_actions":[{"id": "tr_gas", "label": "Gas transit disruption threat", "cost": 150000, "effect": "ticker", "ticker": "NTG", "mag": 0.04, "cd": 21}]},
	{"id":"alb","name":"Albania","lon":20.1,"lat":40.7,"gdp":15.3,"pop":2.9,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "alb_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"hrv","name":"Croatia","lon":16.4,"lat":45.8,"gdp":60.8,"pop":4.1,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "hrv_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"che","name":"Switzerland","lon":7.5,"lat":46.7,"gdp":0.8,"pop":9,"price":26,"region":"Europe","color":"#E24B4A","amb_actions":[{"id": "ch_banks", "label": "Swiss banking secrecy leak", "cost": 300000, "effect": "sector", "sector": "Finance", "mag": -0.04, "cd": 21}]},
	{"id":"lux","name":"Luxembourg","lon":6.1,"lat":49.7,"gdp":71.1,"pop":0.6,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "lux_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"bel","name":"Belgium","lon":4.8,"lat":50.8,"gdp":533.1,"pop":11.5,"price":14,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "bel_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"nld","name":"Netherlands","lon":5.6,"lat":52.4,"gdp":1.0,"pop":18,"price":28,"region":"Europe","color":"#CC8833","amb_actions":[{"id": "nl_chips", "label": "ASML export license denial", "cost": 400000, "effect": "ticker", "ticker": "CHPX", "mag": -0.06, "cd": 30}]},
	{"id":"prt","name":"Portugal","lon":-8.3,"lat":39.6,"gdp":238.8,"pop":10.3,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "prt_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"esp","name":"Spain","lon":-3.5,"lat":40.1,"gdp":1393.5,"pop":47.1,"price":38,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "esp_diplo", "label": "Negotiate preferential trade terms", "cost": 334437, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"irl","name":"Ireland","lon":-7.8,"lat":53.1,"gdp":388.7,"pop":4.9,"price":11,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "irl_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"ncl","name":"New Caledonia","lon":165.1,"lat":-21.1,"gdp":10.8,"pop":0.3,"price":5,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "ncl_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"slb","name":"Solomon Islands","lon":159.2,"lat":-8.0,"gdp":1.6,"pop":0.7,"price":5,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "slb_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"nzl","name":"New Zealand","lon":172.8,"lat":-39.8,"gdp":206.9,"pop":4.9,"price":0.5,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "nzl_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"aus","name":"Australia","lon":134.0,"lat":-24.1,"gdp":1.7,"pop":26,"price":45,"region":"Oceania","color":"#22AA88","amb_actions":[{"id": "au_mining", "label": "Iron ore export surge", "cost": 200000, "effect": "ticker", "ticker": "XAU", "mag": 0.03, "cd": 14}]},
	{"id":"lka","name":"Sri Lanka","lon":80.7,"lat":7.6,"gdp":84.0,"pop":21.8,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "lka_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"chn","name":"China","lon":106.3,"lat":32.5,"gdp":18.0,"pop":1400,"price":380,"region":"Asia","color":"#E24B4A","amb_actions":[{"id": "cn_rare", "label": "Restrict rare earth exports", "cost": 2500000, "effect": "sector", "sector": "Tech", "mag": -0.07, "cd": 30}, {"id": "cn_stimulus", "label": "Announce stimulus package", "cost": 2000000, "effect": "global", "mag": 0.04, "cd": 30}, {"id": "cn_oil", "label": "Sign major oil purchase agreement", "cost": 1500000, "effect": "ticker", "ticker": "WTI", "mag": 0.05, "cd": 21}]},
	{"id":"twn","name":"Taiwan","lon":120.9,"lat":23.7,"gdp":1127.0,"pop":23.6,"price":30,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "twn_diplo", "label": "Negotiate preferential trade terms", "cost": 270480, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"ita","name":"Italy","lon":11.1,"lat":44.7,"gdp":2003.6,"pop":60.3,"price":52,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "ita_diplo", "label": "Request diplomatic pressure on sector", "cost": 641144, "effect": "global", "mag": 0.015, "cd": 21}, {"id": "ita_sanction", "label": "Impose targeted trade sanction", "cost": 961716, "effect": "global", "mag": -0.02, "cd": 30}]},
	{"id":"dnk","name":"Denmark","lon":9.0,"lat":56.0,"gdp":350.1,"pop":5.8,"price":11,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "dnk_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"gbr","name":"United Kingdom","lon":-2.1,"lat":54.4,"gdp":3.1,"pop":67,"price":78,"region":"Europe","color":"#1D9E75","amb_actions":[{"id": "uk_finance", "label": "City of London deregulation", "cost": 400000, "effect": "sector", "sector": "Finance", "mag": 0.04, "cd": 21}, {"id": "uk_intel", "label": "Share intelligence report", "cost": 200000, "effect": "global", "mag": 0.015, "cd": 14}]},
	{"id":"isl","name":"Iceland","lon":-18.7,"lat":64.8,"gdp":24.2,"pop":0.4,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "isl_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"aze","name":"Azerbaijan","lon":47.2,"lat":40.4,"gdp":48.0,"pop":10.0,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "aze_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"geo","name":"Georgia","lon":43.7,"lat":41.9,"gdp":17.5,"pop":3.7,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "geo_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"phl","name":"Philippines","lon":122.5,"lat":11.2,"gdp":376.8,"pop":108.1,"price":12,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "phl_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"mys","name":"Malaysia","lon":113.8,"lat":2.5,"gdp":364.7,"pop":31.9,"price":12,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "mys_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"brn","name":"Brunei","lon":114.6,"lat":4.4,"gdp":13.5,"pop":0.4,"price":5,"region":"Asia","color":"#CC4444","amb_actions":[{"id": "brn_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"svn","name":"Slovenia","lon":14.9,"lat":46.1,"gdp":54.2,"pop":2.1,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "svn_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"fin","name":"Finland","lon":27.3,"lat":63.3,"gdp":269.3,"pop":5.5,"price":11,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "fin_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"svk","name":"Slovakia","lon":19.0,"lat":48.7,"gdp":105.1,"pop":5.5,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "svk_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"cze","name":"Czechia","lon":15.4,"lat":49.9,"gdp":250.7,"pop":10.7,"price":9,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "cze_diplo", "label": "Negotiate preferential trade terms", "cost": 150000, "effect": "global", "mag": 0.01, "cd": 21}]},
	{"id":"eri","name":"Eritrea","lon":38.3,"lat":15.8,"gdp":2.1,"pop":6.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "eri_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"jpn","name":"Japan","lon":138.4,"lat":36.1,"gdp":4.2,"pop":125,"price":84,"region":"Asia","color":"#E24B4A","amb_actions":[{"id": "jp_yen", "label": "Weaken yen for exports", "cost": 600000, "effect": "sector", "sector": "Tech", "mag": 0.03, "cd": 21}, {"id": "jp_boj", "label": "BoJ yield curve control", "cost": 500000, "effect": "ticker", "ticker": "GIDX", "mag": 0.03, "cd": 21}]},
	{"id":"pry","name":"Paraguay","lon":-60.1,"lat":-21.7,"gdp":38.1,"pop":7.0,"price":5,"region":"S America","color":"#639922","amb_actions":[{"id": "pry_res", "label": "Agricultural export priority deal", "cost": 100000, "effect": "ticker", "ticker": "WTI", "mag": 0.015, "cd": 21}]},
	{"id":"yem","name":"Yemen","lon":45.9,"lat":15.3,"gdp":22.6,"pop":29.2,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "yem_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"sau","name":"Saudi Arabia","lon":44.7,"lat":23.8,"gdp":1.1,"pop":36,"price":35,"region":"Middle East","color":"#EF9F27","amb_actions":[{"id": "sa_cut", "label": "OPEC production cut signal", "cost": 400000, "effect": "ticker", "ticker": "WTI", "mag": 0.08, "cd": 21}, {"id": "sa_increase", "label": "Flood market with oil", "cost": 400000, "effect": "ticker", "ticker": "WTI", "mag": -0.08, "cd": 21}]},
	{"id":"ata","name":"Antarctica","lon":35.9,"lat":-79.8,"gdp":0.9,"pop":0.0,"price":5,"region":"Other","color":"#666666","amb_actions":[{"id": "ata_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"cyn","name":"Northern Cyprus","lon":33.7,"lat":35.2,"gdp":3.6,"pop":0.3,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "cyn_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"cyp","name":"Cyprus","lon":33.1,"lat":34.9,"gdp":24.9,"pop":1.2,"price":5,"region":"Middle East","color":"#CCAA22","amb_actions":[{"id": "cyp_trade", "label": "Regional supply chain agreement", "cost": 100000, "effect": "sector", "sector": "Tech", "mag": 0.015, "cd": 21}]},
	{"id":"mar","name":"Morocco","lon":-7.2,"lat":31.7,"gdp":119.7,"pop":36.5,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "mar_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"egy","name":"Egypt","lon":29.4,"lat":26.2,"gdp":0.4,"pop":105,"price":12,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "eg_suez", "label": "Suez canal partial closure", "cost": 200000, "effect": "ticker", "ticker": "WTI", "mag": 0.05, "cd": 21}]},
	{"id":"lby","name":"Libya","lon":18.0,"lat":26.6,"gdp":52.1,"pop":6.8,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "lby_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"eth","name":"Ethiopia","lon":39.1,"lat":8.0,"gdp":95.9,"pop":112.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "eth_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"dji","name":"Djibouti","lon":42.5,"lat":12.0,"gdp":3.3,"pop":1.0,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "dji_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"sol","name":"Somaliland","lon":46.7,"lat":9.4,"gdp":17.8,"pop":5.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "sol_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"uga","name":"Uganda","lon":32.9,"lat":2.0,"gdp":35.2,"pop":44.3,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "uga_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"rwa","name":"Rwanda","lon":30.1,"lat":-1.9,"gdp":10.4,"pop":12.6,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "rwa_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
	{"id":"bih","name":"Bosnia and Herzegovina","lon":18.1,"lat":44.1,"gdp":20.2,"pop":3.3,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "bih_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"mkd","name":"North Macedonia","lon":21.6,"lat":41.6,"gdp":12.5,"pop":2.1,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "mkd_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"srb","name":"Republic of Serbia","lon":20.8,"lat":44.2,"gdp":51.5,"pop":6.9,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "srb_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"mne","name":"Montenegro","lon":19.1,"lat":42.8,"gdp":5.5,"pop":0.6,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "mne_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"kos","name":"Kosovo","lon":20.9,"lat":42.6,"gdp":7.9,"pop":1.8,"price":5,"region":"Europe","color":"#7766CC","amb_actions":[{"id": "kos_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"tto","name":"Trinidad and Tobago","lon":-60.9,"lat":11.0,"gdp":24.3,"pop":1.4,"price":5,"region":"N America","color":"#378ADD","amb_actions":[{"id": "tto_trade", "label": "Bilateral trade facilitation", "cost": 100000, "effect": "global", "mag": 0.008, "cd": 21}]},
	{"id":"sds","name":"South Sudan","lon":30.4,"lat":7.2,"gdp":12.0,"pop":11.1,"price":5,"region":"Africa","color":"#CC8833","amb_actions":[{"id": "sds_res", "label": "Secure resource extraction rights", "cost": 100000, "effect": "ticker", "ticker": "XAU", "mag": 0.02, "cd": 21}]},
]

const REGION_COLORS := {
	"Africa":    "#C8821A",
	"Asia":      "#CC3333",
	"Europe":    "#3A7BC8",
	"N America": "#8844BB",
	"S America": "#D45A00",
	"Oceania":   "#1A9AAA",
}

func get_color(cid: String) -> String:
	var c := find_country(cid)
	return REGION_COLORS.get(c.get("region",""), "#444455")

var _last_month: int = -1

func _ready() -> void:
	_last_month = GameState.game_month
	GameState.day_advanced.connect(_on_day)

func _on_day(_d: String) -> void:
	if owned.is_empty(): return
	if GameState.game_month != _last_month:
		_last_month = GameState.game_month
		Portfolio.grant("XAU", float(owned.size()))

func can_afford(cid:String)->bool:
	var c:=find_country(cid); if c.is_empty(): return false
	return GameState.cash>=float(c["price"])*1_000_000.0

func buy(cid:String)->bool:
	if cid in owned: return false
	var c:=find_country(cid); if c.is_empty(): return false
	var price:=float(c["price"])*1_000_000.0
	if GameState.cash<price: return false
	GameState.add_cash(-price); owned.append(cid)
	emit_signal("country_purchased",c); return true

func is_owned(cid:String)->bool: return cid in owned
func get_all()->Array: return COUNTRIES

func get_owned_with_actions()->Array:
	var out:=[]; for cid in owned:
		var c:=find_country(cid)
		if not c.is_empty(): out.append(c)
	return out

func find_country(cid:String)->Dictionary:
	for c in COUNTRIES: if c["id"]==cid: return c
	return {}