extends Node

const BILLIONAIRES := [
	[1,"Ethan Marsh",215.0,"Electric vehicles / Space"],
	[2,"James Belton",186.0,"E-commerce / Cloud"],
	[3,"Bernard Arnaud",170.0,"Luxury goods"],
	[4,"William Gaines",132.0,"Software / Philanthropy"],
	[5,"Lawrence Ellis",128.0,"Enterprise software"],
	[6,"Marcus Zeller",124.0,"Social media"],
	[7,"Walter Burnett",119.0,"Investments / Insurance"],
	[8,"Leonard Parks",114.0,"Internet / Venture capital"],
	[9,"Stefan Bryn",108.0,"Internet / AI"],
	[10,"Steven Ballard",95.0,"Software"],
	[11,"Carlos Slender",93.0,"Telecom / Retail"],
	[12,"François Pinot",89.0,"Luxury / Wine"],
	[13,"Michael Bloom",86.0,"Financial data"],
	[14,"Alice Walton-Cole",84.0,"Retail (heir)"],
	[15,"Jim Walton-Cole",82.0,"Retail (heir)"],
	[16,"Rob Walton-Cole",80.0,"Retail (heir)"],
	[17,"Mukesh Ambrose",77.0,"Petrochemicals / Retail"],
	[18,"Amancio Ortuño",75.0,"Fast fashion"],
	[19,"Gautam Aiden",72.0,"Ports / Infrastructure"],
	[20,"Jensen Huang-Li",70.0,"Semiconductors / AI"],
	[21,"Zhong Chen",68.0,"Beverages"],
	[22,"Michael Dell-Park",65.0,"Computers / Tech"],
	[23,"MacKenzie Watts",63.0,"Philanthropy / Media"],
	[24,"He Xiangjun",60.0,"Gaming / Music"],
	[25,"Phil Knight-Chang",58.0,"Sportswear"],
	[26,"Ken Griffin",56.0,"Hedge funds"],
	[27,"Ray Dalio",54.0,"Macro investing"],
	[28,"Steve Cohen",52.0,"Quantitative trading"],
	[29,"Jorge Paulo Lemos",51.0,"Beer / Consumer goods"],
	[30,"Jacqueline Mars-Hill",49.0,"Confectionery (heir)"],
	[31,"John Mars-Hill",48.0,"Confectionery (heir)"],
	[32,"Dieter Schwartz",46.0,"Discount retail"],
	[33,"Thomas Klatten",45.0,"Automotive (heir)"],
	[34,"Klaus-Michael Kühne",44.0,"Logistics"],
	[35,"Len Blaufein",43.0,"Real estate"],
	[36,"Peter Thiele",42.0,"Fintech / Venture capital"],
	[37,"David Teldon",41.0,"Media"],
	[38,"Mark Cubano",40.0,"Sports / Media"],
	[39,"Stephen Roth",39.0,"Real estate"],
	[40,"Gianluigi Berluscone",38.0,"Media (heir)"],
	[41,"Henry Sy Jr.",37.0,"Retail (heir)"],
	[42,"Ma Huating",36.0,"Internet / Gaming"],
	[43,"Robin Li-Chen",35.0,"Search / AI"],
	[44,"Jack Mao",34.0,"E-commerce"],
	[45,"Pony Ma-Li",33.0,"Social media / Gaming"],
	[46,"Zhang Yiming",32.0,"Short video / AI"],
	[47,"Wang Jianlin",31.0,"Real estate / Entertainment"],
	[48,"Ding Lei-Yan",30.0,"Gaming"],
	[49,"Colin Huang-Xu",29.5,"E-commerce"],
	[50,"Liu Qiangdong",29.0,"E-commerce"],
	[51,"Eric Yuan-Wang",28.5,"Video conferencing"],
	[52,"Patrick Collinson",28.0,"Payments"],
	[53,"John Collinson",27.5,"Payments"],
	[54,"Reed Hastings",26.5,"Streaming"],
	[55,"David Benioff-Sp",26.0,"Cloud software"],
	[56,"Brian Chesky",25.0,"Hospitality tech"],
	[57,"Bobby Kotick",24.0,"Gaming"],
	[58,"Rupert Murdock",23.5,"Media"],
	[59,"Harold Hamm",21.5,"Oil & Gas"],
	[60,"Richard Kinder",21.0,"Pipelines"],
	[61,"Alan Howard",20.5,"Hedge funds"],
	[62,"Izzy Englander",20.0,"Quantitative trading"],
	[63,"Dan Sundheim",19.5,"Equity investments"],
	[64,"Chamath Pali-H",19.0,"Venture capital"],
	[65,"Marc Andreessen",18.5,"Venture capital"],
	[66,"Ben Horowitz",18.0,"Venture capital"],
	[67,"John Doerr",17.5,"Venture capital"],
	[68,"Masayoshi Sohn",17.0,"Tech investments"],
	[69,"Son Jaeyong",16.5,"Electronics (heir)"],
	[70,"Lee Jae-wook",16.0,"Electronics (heir)"],
	[71,"Shiv Nadar",15.5,"IT services"],
	[72,"N.R. Murthy",15.0,"IT services"],
	[73,"Azim Premji",14.5,"IT services"],
	[74,"Viktor Rashnikov",13.5,"Steel"],
	[75,"Vladimir Lisin",13.0,"Steel"],
	[76,"Alisher Usmanov",12.5,"Mining / Media"],
	[77,"Roman Abravich",12.0,"Oil & Sports"],
	[78,"Mikhail Prokhorev",11.5,"Finance / Sports"],
	[79,"Vagit Alekperev",11.0,"Oil"],
	[80,"Leonid Fedun",10.5,"Oil"],
	[81,"Isak Andic",9.8,"Fashion retail"],
	[82,"Anders Povlsen",9.5,"Fashion"],
	[83,"Stefan Quandt",9.2,"Automotive (heir)"],
	[84,"Reinhold Würth",9.0,"Industrial fasteners"],
	[85,"Georg Schaeffler",8.7,"Automotive parts"],
	[86,"Hasso Plattner",8.4,"Enterprise software"],
	[87,"Dietmar Hopp",8.1,"Enterprise software"],
	[88,"Klaus Tschira",7.9,"Software (heir)"],
	[89,"Christoph Brandstetter",7.6,"Insurance"],
	[90,"Marcel Herrmann Ternes",7.3,"Chemicals"],
	[91,"Gina Rinehart",7.0,"Mining"],
	[92,"Anthony Pratt",6.8,"Packaging"],
	[93,"Andrew Forrest",6.5,"Mining"],
	[94,"Kerry Stokes",6.2,"Media"],
	[95,"James Packer",5.9,"Casinos"],
	[96,"Tadashi Yanai",5.7,"Fashion retail"],
	[97,"Masatoshi Ito",5.4,"Retail (heir)"],
	[98,"Hiroshi Mikitani",5.1,"E-commerce"],
	[99,"Nobutada Saji",4.9,"Beverages (heir)"],
	[100,"Takahisa Takahara",4.7,"Consumer goods"],
]

func get_player_rank() -> int:
	var nw_b := GameState.get_net_worth() / 1_000_000_000.0
	for i in BILLIONAIRES.size():
		if nw_b >= BILLIONAIRES[i][2]: return BILLIONAIRES[i][0]
	return 101

func get_nearest_entries(count: int = 10) -> Array:
	var pr := get_player_rank()
	var start := maxi(0, pr - 4)
	var end_  := mini(BILLIONAIRES.size(), start + count)
	var result := []
	for i in range(start, end_): result.append(BILLIONAIRES[i])
	return result

func get_top_entries(count: int = 10) -> Array:
	return BILLIONAIRES.slice(0, mini(count, BILLIONAIRES.size()))
